"""Generate the Crawling Clock's d20 as hand-inked SVG.

The die is computed, not drawn: a real icosahedron is rotated until one face points
at the viewer, the back faces are dropped, and the ten front faces are filled with
pen hatching whose density follows the lighting. The face pointing at the viewer is
left bare — that is the plate the counter sits on.

Every stroke is generated here, so the artwork is ours. Run it to regenerate:

    uv run --with numpy python tools/d20/generate-d20.py

It rewrites module/src/crawling-clock-d20.js. The seed is fixed, so the output is
stable; change it for a different hand.
"""

import numpy as np, random
from pathlib import Path

random.seed(11)

phi = (1 + 5 ** 0.5) / 2
V = []
for s1 in (1, -1):
    for s2 in (1, -1):
        V += [(0, s1, s2 * phi), (s1, s2 * phi, 0), (s1 * phi, 0, s2)]
V = np.array(sorted(set(V))); V = V / np.linalg.norm(V[0])
edge = min(np.linalg.norm(V[i]-V[j]) for i in range(12) for j in range(12) if i != j)
faces = [(i,j,k) for i in range(12) for j in range(i+1,12) for k in range(j+1,12)
         if all(abs(np.linalg.norm(V[a]-V[b]) - edge) < 1e-6 for a,b in ((i,j),(j,k),(i,k)))]

# Rotate a face to point at the viewer, then spin its apex upright.
n = V[list(faces[0])].mean(axis=0); n /= np.linalg.norm(n)
z = np.array([0,0,1.0]); v = np.cross(n,z); c = np.dot(n,z)
K = np.array([[0,-v[2],v[1]],[v[2],0,-v[0]],[-v[1],v[0],0]])
P = V @ (np.eye(3) + K + K@K*(1/(1+c))).T
apex = P[list(faces[0])][np.argmax(P[list(faces[0])][:,1])]
th = np.pi/2 - np.arctan2(apex[1], apex[0])
P = P @ np.array([[np.cos(th),-np.sin(th),0],[np.sin(th),np.cos(th),0],[0,0,1]]).T

s = 46 / np.abs(P[:,:2]).max()
base = [(50 + p[0]*s, 50 - p[1]*s) for p in P]
# One wobble per vertex, shared by every edge and facet that touches it.
pts = [(x + random.uniform(-.5,.5), y + random.uniform(-.5,.5)) for x, y in base]

# Convex solid centred on the origin: the face centroid IS the outward normal.
LIGHT = np.array([-0.4, 0.72, 0.57]); LIGHT /= np.linalg.norm(LIGHT)
vis, top = [], None
for f in faces:
    cen = P[list(f)].mean(axis=0)
    if cen[2] <= 1e-9: continue                      # back face
    nrm = cen / np.linalg.norm(cen)
    shade = max(0.0, float(np.dot(nrm, LIGHT)))
    if cen[2] > 0.99 * max(P[list(g)].mean(axis=0)[2] for g in faces):
        top = f; continue                            # the number's plate stays bare
    vis.append((f, shade))
print('visible facets:', len(vis), '+ top face')

def inside(poly, x, y, margin=.07):
    (x1,y1),(x2,y2),(x3,y3) = poly
    d = (y2-y3)*(x1-x3) + (x3-x2)*(y1-y3)
    a = ((y2-y3)*(x-x3) + (x3-x2)*(y-y3))/d
    b = ((y3-y1)*(x-x3) + (x1-x3)*(y-y3))/d
    return a >= margin and b >= margin and (1-a-b) >= margin

def hatch(poly, density, angle):
    xs = [p[0] for p in poly]; ys = [p[1] for p in poly]
    cx, cy = sum(xs)/3, sum(ys)/3
    ca, sa = np.cos(angle), np.sin(angle)
    span = max(max(xs)-min(xs), max(ys)-min(ys))
    step = max(0.75, 3.2 - 2.4*density)     # lit faces get sparser strokes
    lines, t = [], -span
    while t <= span:
        seg = []
        for u in np.linspace(-span, span, 48):
            x, y = cx + ca*u - sa*t, cy + sa*u + ca*t
            if inside(poly, x, y):
                seg.append((x + random.uniform(-.18,.18), y + random.uniform(-.18,.18)))
            elif len(seg) > 2:
                lines.append(seg); seg = []
            else:
                seg = []
        if len(seg) > 2: lines.append(seg)
        t += step * random.uniform(.82, 1.18)
    return lines

out = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" class="cc-d20" aria-hidden="true">',
       '<g class="cc-d20__hatch">']
for f, shade in vis:
    poly = [pts[i] for i in f]
    for seg in hatch(poly, shade, random.uniform(0, np.pi)):
        out.append('<path d="M' + ' L'.join(f'{x:.1f},{y:.1f}' for x, y in seg) + '"/>')
out.append('</g>')

# Each unique edge of a visible face, drawn once, bowed slightly like an inked line.
edges = set()
for f, _ in vis + [(top, 0)]:
    for a, b in ((f[0],f[1]), (f[1],f[2]), (f[0],f[2])):
        edges.add((min(a,b), max(a,b)))
out.append('<g class="cc-d20__edges">')
for a, b in sorted(edges):
    (x1,y1), (x2,y2) = pts[a], pts[b]
    mx, my = (x1+x2)/2, (y1+y2)/2
    dx, dy = x2-x1, y2-y1
    L = (dx*dx+dy*dy) ** .5
    o = random.uniform(-.6,.6)
    out.append(f'<path d="M{x1:.1f},{y1:.1f} Q{mx - dy/L*o:.1f},{my + dx/L*o:.1f} {x2:.1f},{y2:.1f}"/>')
out.append('</g></svg>')
svg = '\n'.join(out)

dest = Path(__file__).resolve().parents[2] / 'module' / 'src' / 'crawling-clock-d20.js'
dest.write_text(
    "// Generated by tools/d20/generate-d20.py — do not edit by hand.\n"
    "//\n"
    "// A real icosahedron viewed face-on: hexagonal silhouette, ten visible facets,\n"
    "// pen hatching whose density follows the lighting. The centre face is left bare\n"
    "// for the counter. Carries classes only — all colour lives in the stylesheet.\n"
    "\n"
    "export const CRAWLING_CLOCK_D20 = `\n" + svg + "\n`;\n"
)
print('paths:', sum(1 for l in out if l.startswith('<path')))
print('top face 2D:', [tuple(round(v, 1) for v in pts[i]) for i in top])
print('wrote', dest)
